<?php

    return array(
    'affinityWSDL'      =>  "https://api.affinity.akjl.co.uk/[APIuser]/WSDL/AffinityAPIService.WSDL",
    'affinityUserName'  =>  "[AffinityUsername]",
    'affinityPassword'  =>  "[AffinityPassword]",
    'affinityAppName'   =>  "[AppName]",
    'affinityAppRef'    =>  "[LaravelAPI]",
    'serviceID'         =>  [
        0 => ["Service" => "INDIRECT", "Enabled" => 1],
        1 => ["Service" => "Leakage", "Enabled" => 1],
        4 => ["Service" => "ALTERNATIVE", "Enabled" => 1]
    ],
    'billingFrequencyID' => [
        0  => ["Frequency" => "Monthly", "Enabled" => 1],
        1  => ["Frequency" => "Quarterly", "Enabled" => 1],
        2  => ["Frequency" => "Annual", "Enabled" => 1],
        3  => ["Frequency" => "Single", "Enabled" => 1],
        4  => ["Frequency" => "SixMonthly", "Enabled" => 1],
        5  => ["Frequency" => "FourMonthly", "Enabled" => 1],
        6  => ["Frequency" => "TwoMonthly", "Enabled" => 1],
        10 => ["Frequency" => "One-Off", "Enabled" => 1]
    ],
    'productServiceCodeID' => [
        0  => ["ProductCode" => "MAINTENANCE", "Enabled" => 1, "ServiceGroup" => "MAINTENANCE"],
        1  => ["ProductCode" => "NUMBER RENTAL", "Enabled" => 1, "ServiceGroup" => "NTS"],
        2  => ["ProductCode" => "INTERNET", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        3  => ["ProductCode" => "EQUIPMENT", "Enabled" => 1, "ServiceGroup" => "OTHER"],
        4  => ["ProductCode" => "DISCOUNT SCHEME", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        5  => ["ProductCode" => "SERVICE", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        6  => ["ProductCode" => "CONNECTION", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        7  => ["ProductCode" => "I-SERVICES", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        8  => ["ProductCode" => "I-CONNECTIONS", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        9  => ["ProductCode" => "REFUND", "Enabled" => 1, "ServiceGroup" => "REFUND"],
        10 => ["ProductCode" => "I-REFUND", "Enabled" => 1, "ServiceGroup" => "REFUND"],
        11 => ["ProductCode" => "BUNDLE", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        12 => ["ProductCode" => "ELEC UNIT CHARGE", "Enabled" => 1, "ServiceGroup" => NULL],
        13 => ["ProductCode" => "ELEC STANDING CHARGE", "Enabled" => 1, "ServiceGroup" => NULL],
        14 => ["ProductCode" => "ELEC CCL", "Enabled" => 1, "ServiceGroup" => NULL],
        15 => ["ProductCode" => "SETTLEMENT", "Enabled" => 1, "ServiceGroup" => NULL],
        16 => ["ProductCode" => "PC CONNECTION", "Enabled" => 1, "ServiceGroup" => NULL],
        17 => ["ProductCode" => "PC RENTAL", "Enabled" => 1, "ServiceGroup" => NULL],
        18 => ["ProductCode" => "DC CONNECTION", "Enabled" => 1, "ServiceGroup" => NULL],
        19 => ["ProductCode" => "DC RENTAL", "Enabled" => 1, "ServiceGroup" => NULL],
        20 => ["ProductCode" => "MINIMUM CALL CHARGES", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        21 => ["ProductCode" => " CONSULTANCY", "Enabled" => 1, "ServiceGroup" => "OTHER"],
        22 => ["ProductCode" => "BROADBAND SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        23 => ["ProductCode" => " BROADBAND CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        24 => ["ProductCode" => "DELIVERY", "Enabled" => 1, "ServiceGroup" => "OTHER"],
        25 => ["ProductCode" => " COLO CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        26 => ["ProductCode" => " COLO SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        27 => ["ProductCode" => "DIAL UP CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        28 => ["ProductCode" => "DIAL UP SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        29 => ["ProductCode" => " DOMAIN CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        30 => ["ProductCode" => " DOMAIN SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        31 => ["ProductCode" => "EMAIL CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        32 => ["ProductCode" => "EMAIL SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        33 => ["ProductCode" => "WEB CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        34 => ["ProductCode" => "WEB SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        35 => ["ProductCode" => "BLACKBERRY SERVICE", "Enabled" => 1, "ServiceGroup" => NULL],
        36 => ["ProductCode" => "BLACKBERRY CONNECTION", "Enabled" => 1, "ServiceGroup" => NULL],
        37 => ["ProductCode" => "INTERNET CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        38 => ["ProductCode" => "INTERNET SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        39 => ["ProductCode" => "ADMINISTRATIVE", "Enabled" => 1, "ServiceGroup" => NULL],
        40 => ["ProductCode" => "BLACKBERRY SOFTWARE", "Enabled" => 1, "ServiceGroup" => NULL],
        41 => ["ProductCode" => "CALL DEPENDENT", "Enabled" => 1, "ServiceGroup" => NULL],
        42 => ["ProductCode" => "VOIP SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        43 => ["ProductCode" => "VOIP CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        44 => ["ProductCode" => "INSURANCE", "Enabled" => 1, "ServiceGroup" => "OTHER"],
        45 => ["ProductCode" => "VOIP EQUIPMENT", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        46 => ["ProductCode" => "CCTV", "Enabled" => 1, "ServiceGroup" => NULL],
        47 => ["ProductCode" => "DATA BACKUP", "Enabled" => 1, "ServiceGroup" => NULL],
        48 => ["ProductCode" => "ITEMISATION", "Enabled" => 1, "ServiceGroup" => NULL],
        49 => ["ProductCode" => "CENTREX", "Enabled" => 1, "ServiceGroup" => NULL],
        50 => ["ProductCode" => "TERMINATION", "Enabled" => 1, "ServiceGroup" => NULL],
        51 => ["ProductCode" => "INTERNET DISCOUNT", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        52 => ["ProductCode" => "NETGUARD", "Enabled" => 1, "ServiceGroup" => NULL],
        53 => ["ProductCode" => "DATA VAULT", "Enabled" => 1, "ServiceGroup" => NULL],
        54 => ["ProductCode" => "NET STORE", "Enabled" => 1, "ServiceGroup" => NULL],
        55 => ["ProductCode" => "E-FAX (PROVISION)", "Enabled" => 1, "ServiceGroup" => NULL],
        56 => ["ProductCode" => "DATA PRODUCT BUNDLE", "Enabled" => 1, "ServiceGroup" => NULL],
        57 => ["ProductCode" => "ADVANCE SERVICE", "Enabled" => 1, "ServiceGroup" => NULL],
        58 => ["ProductCode" => "LINE SERVICES", "Enabled" => 1, "ServiceGroup" => "FIXED"]
     ],
    "SiteCLIServicesID" => [
        0  => ["CLIService" => "LINE RENTAL", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        1  => ["CLIService" => "INSURANCE", "Enabled" => 1, "ServiceGroup" => NULL],
        2  => ["CLIService" => "EQUIPMENT", "Enabled" => 1, "ServiceGroup" => NULL],
        3  => ["CLIService" => "ADVANCED LINE RENTAL", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        4  => ["CLIService" => "INCLUSIVE CALLS", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        5  => ["CLIService" => "ITEMISATION", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        6  => ["CLIService" => "DISCOUNT", "Enabled" => 1, "ServiceGroup" => "OTHER"],
        7  => ["CLIService" => "REFUND", "Enabled" => 1, "ServiceGroup" => "REFUND"],
        8  => ["CLIService" => "PSTN LINE RENTAL", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        9  => ["CLIService" => "SELECT SERVICES", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        10 => ["CLIService" => "CONNECTION CHARGE", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        11 => ["CLIService" => "INSTALLATION CHARGE", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        12 => ["CLIService" => "ITS", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        13 => ["CLIService" => "GPRS SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        14 => ["CLIService" => "INTERNET RENTAL", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        15 => ["CLIService" => "INTERNET ADV RENTAL", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        16 => ["CLIService" => "BOLT ON 1", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        17 => ["CLIService" => "BOLT ON 2", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        18 => ["CLIService" => "APN CHARGE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        19 => ["CLIService" => "MAIL NOW LINE RENTAL", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        20 => ["CLIService" => "MINIMUM CALL CHARGES", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        21 => ["CLIService" => "BUNDLE", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        22 => ["CLIService" => "NUMBER RENTAL", "Enabled" => 1, "ServiceGroup" => "NTS"],
        23 => ["CLIService" => "MAINTENANCE", "Enabled" => 1, "ServiceGroup" => "MAINTENANCE"],
        24 => ["CLIService" => "INTERNET CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        25 => ["CLIService" => "WIFI CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        26 => ["CLIService" => "WIFI SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        27 => ["CLIService" => "BROADBAND CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        28 => ["CLIService" => "BROADBAND SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        29 => ["CLIService" => "3G CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        30 => ["CLIService" => "3G SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        31 => ["CLIService" => "GPRS CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        32 => ["CLIService" => "DIAL UP CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        33 => ["CLIService" => "DIAL UP SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        34 => ["CLIService" => "CALL DEPENDENT", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        35 => ["CLIService" => "DELIVERY", "Enabled" => 1, "ServiceGroup" => "OTHER"],
        36 => ["CLIService" => "BLACKBERRY SERVICE", "Enabled" => 1, "ServiceGroup" => NULL],
        37 => ["CLIService" => "BLACKBERRY ADV SERVICE", "Enabled" => 1, "ServiceGroup" => NULL],
        38 => ["CLIService" => "BROADBAND ADV SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        39 => ["CLIService" => "BOLT ON MINUTES", "Enabled" => 1, "ServiceGroup" => NULL],
        40 => ["CLIService" => "VOIP SERVICE", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        41 => ["CLIService" => "VOIP CONNECTION", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        42 => ["CLIService" => "DISCONNECTION", "Enabled" => 1, "ServiceGroup" => NULL],
        43 => ["CLIService" => "CENTREX", "Enabled" => 1, "ServiceGroup" => NULL],
        44 => ["CLIService" => "INTERNET DISCOUNT", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        45 => ["CLIService" => "TERMINATION", "Enabled" => 1, "ServiceGroup" => NULL],
        46 => ["CLIService" => "NETWORK BROADBAND", "Enabled" => 1, "ServiceGroup" => "BROADBAND"],
        47 => ["CLIService" => "NO CALL DEPENDENT", "Enabled" => 1, "ServiceGroup" => NULL],
        48 => ["CLIService" => "E-FAX", "Enabled" => 1, "ServiceGroup" => NULL],
        49 => ["CLIService" => "LINE SERVICES", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        50 => ["CLIService" => "LINE RENTAL SUBSIDY", "Enabled" => 1, "ServiceGroup" => "FIXED"],
        52 => ["CLIService" => "ASM", "Enabled" => 1, "ServiceGroup" => "OTHER"],
        56 => ["CLIService" => "BROADBAND EQUIPMENT", "Enabled" => 1, "ServiceGroup" => "BROADBAND"]
    ]

);